# Site settings
title: Joris van Vugt
email: mail@jorisvanvugt.com
url: https://jorisvanvugt.com
description: "Personal website of Joris van Vugt"
keywords: "data, science, machine, learning, programming, artificial, intelligence"
skills: "R&D Engineer Autonomous Driving at TomTom"
meta_author: van Vugt, Joris

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Joris van Vugt
  location: Location
  social: Around the Web
  credits: Details

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jvanvugt
  - title: linkedin
    url: https://www.linkedin.com/in/joris-van-vugt-506571109/
  - title: envelope
    url: mailto:mail@jorisvanvugt.com


# Postal address (add as many lines as necessary)
address:
  - line: Utrecht, The Netherlands

# Credits content
credits:

# Build settings
markdown: kramdown
permalink: pretty
